name: Generate Snake Animation

on:
  schedule:
    # Runs at 5:00 UTC every day
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Generate the snake animation
      - uses: Platane/snk@v2
        with:
          github_user_name: NightDevilPT
          outputs: dist/snake.svg

      # Push the SVG file to the repository
      - name: Push Snake
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.SNAKE_TOKEN }}
          branch: main
          force: true
